baseURL = 'https://moritzwilksch.github.io/'
languageCode = 'en-us'
title = 'Moritz Wilksch'
theme = "PaperMod"

[params]
[params.assets]
favicon = "favicon/favicon.svg"
favicon16x16 = "favicon/favicon-16x16.png"
favicon32x32 = "favicon/favicon-32x32.png"
apple_touch_icon = "favicon/apple-touch-icon.png"

[params.profileMode]
enabled = true
title = "Moritz Wilksch"
subtitle = "Machine Learning Engineer"
imageUrl = "images/profile-pic-new-small.jpg"
imageTitle = "profile picture"
imageWidth = 200
imageHeight = 200

[[params.profileMode.buttons]]
name = "About"
url = "/about"

[[params.profileMode.buttons]]
name = "Blog"
url = "/blog"

[[params.profileMode.buttons]]
name = "Github"
url = "https://github.com/moritzwilksch"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://linkedin.com/in/moritzwilksch"

[[params.socialIcons]]
name = "github"
url = "https://github.com/moritzwilksch"
