[workspace]
name = "moritzwilksch.github.io"
version = "0.1.0"
description = "personal website"
authors = ["Moritz Wilksch <moritzwilksch@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[dependencies]
hugo = ">=0.154.5,<0.155"
